[workspace]
authors = ["Amber Kampen <kampen@dnli.com>"]
channels = ["conda-forge", "bioconda"]
name = "maddy_temp"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.0,<3"
scikit-learn = ">=1.7.0,<2"
pip = ">=25.1.1,<26"
openpyxl = ">=3.1.5,<4"
